### ISSUE TITLE
Warning re Log Analytics

### ISSUE THREAD

**Issue by mrochon** [microsoft/AzureOpenAI-with-APIM#7]
I am getting this warning in the Azure portal when viewing the Log Analytics workspace of this deployment:

> The Log Analytics agents (MMA.OMS) used to collect logs from virtual machines and servers will no longer be supported from August 31, 2024. Plan to migrate to Azure Monitor Agent before this date. [Learn more about migrating to Azure Monitor Agent](https://go.microsoft.com/fwlink/?linkid=2219988)

Any plans to update to use the Monitor Agent?

**Comment by paullizer** [comment]
This is a general alert message for Log Analytics workspace.
